/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DeliveryLineItem = IDL.Record({
  'qty' : IDL.Int,
  'subCategory' : IDL.Text,
  'godownId' : IDL.Text,
  'itemName' : IDL.Text,
  'category' : IDL.Text,
});
export const DeliveryEntry = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'deliveredBy' : IDL.Text,
  'customerPhone' : IDL.Text,
  'businessId' : IDL.Text,
  'createdAt' : IDL.Int,
  'deliveryType' : IDL.Text,
  'biltyNumber' : IDL.Text,
  'items' : IDL.Vec(DeliveryLineItem),
});
export const GodownQty = IDL.Record({ 'qty' : IDL.Int, 'godownId' : IDL.Text });
export const InventoryItem = IDL.Record({
  'id' : IDL.Text,
  'subCategory' : IDL.Text,
  'businessId' : IDL.Text,
  'purchaseRate' : IDL.Float64,
  'godownQtys' : IDL.Vec(GodownQty),
  'shopQty' : IDL.Int,
  'itemName' : IDL.Text,
  'category' : IDL.Text,
  'saleRate' : IDL.Float64,
});
export const QueueBale = IDL.Record({
  'status' : IDL.Text,
  'baleLabel' : IDL.Text,
  'itemName' : IDL.Text,
  'category' : IDL.Text,
});
export const QueueEntry = IDL.Record({
  'id' : IDL.Text,
  'businessId' : IDL.Text,
  'supplier' : IDL.Text,
  'createdAt' : IDL.Int,
  'transport' : IDL.Text,
  'biltyNumber' : IDL.Text,
  'bales' : IDL.Vec(QueueBale),
  'delivered' : IDL.Bool,
  'enteredBy' : IDL.Text,
});
export const SaleLineItem = IDL.Record({
  'qty' : IDL.Int,
  'subCategory' : IDL.Text,
  'rate' : IDL.Float64,
  'itemName' : IDL.Text,
  'category' : IDL.Text,
});
export const SaleEntry = IDL.Record({
  'id' : IDL.Text,
  'businessId' : IDL.Text,
  'createdAt' : IDL.Int,
  'recordedBy' : IDL.Text,
  'items' : IDL.Vec(SaleLineItem),
});
export const SubCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'fieldType' : IDL.Text,
});
export const TransitEntry = IDL.Record({
  'id' : IDL.Text,
  'businessId' : IDL.Text,
  'packages' : IDL.Int,
  'supplier' : IDL.Text,
  'createdAt' : IDL.Int,
  'transport' : IDL.Text,
  'biltyNumber' : IDL.Text,
  'itemName' : IDL.Text,
  'category' : IDL.Text,
  'enteredBy' : IDL.Text,
  'biltyDate' : IDL.Text,
});
export const TxType = IDL.Variant({
  'directStock' : IDL.Null,
  'sale' : IDL.Null,
  'inward' : IDL.Null,
  'delivery' : IDL.Null,
  'transfer' : IDL.Null,
});
export const TxRecord = IDL.Record({
  'id' : IDL.Text,
  'qty' : IDL.Int,
  'subCategory' : IDL.Text,
  'businessId' : IDL.Text,
  'createdAt' : IDL.Int,
  'rate' : IDL.Float64,
  'transport' : IDL.Text,
  'toLocation' : IDL.Text,
  'fromLocation' : IDL.Text,
  'biltyNumber' : IDL.Text,
  'notes' : IDL.Text,
  'itemName' : IDL.Text,
  'category' : IDL.Text,
  'txType' : TxType,
  'enteredBy' : IDL.Text,
});
export const Role = IDL.Variant({
  'admin' : IDL.Null,
  'supplier' : IDL.Null,
  'staff' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BiltyPrefix = IDL.Record({ 'id' : IDL.Text, 'prefix' : IDL.Text });
export const Business = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
export const Category = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'subCategories' : IDL.Vec(SubCategory),
});
export const Godown = IDL.Record({
  'id' : IDL.Text,
  'businessId' : IDL.Text,
  'name' : IDL.Text,
});
export const InwardItem = IDL.Record({
  'subCategory' : IDL.Text,
  'purchaseRate' : IDL.Float64,
  'godownQtys' : IDL.Vec(GodownQty),
  'totalQty' : IDL.Int,
  'shopQty' : IDL.Int,
  'itemName' : IDL.Text,
  'category' : IDL.Text,
  'saleRate' : IDL.Float64,
});
export const InwardSavedEntry = IDL.Record({
  'id' : IDL.Text,
  'businessId' : IDL.Text,
  'supplier' : IDL.Text,
  'transport' : IDL.Text,
  'biltyNumber' : IDL.Text,
  'savedAt' : IDL.Int,
  'savedBy' : IDL.Text,
  'items' : IDL.Vec(InwardItem),
});
export const TransferEntry = IDL.Record({
  'id' : IDL.Text,
  'qty' : IDL.Int,
  'subCategory' : IDL.Text,
  'businessId' : IDL.Text,
  'createdAt' : IDL.Int,
  'rate' : IDL.Float64,
  'toId' : IDL.Text,
  'toType' : IDL.Text,
  'itemName' : IDL.Text,
  'fromType' : IDL.Text,
  'category' : IDL.Text,
  'fromId' : IDL.Text,
  'transferredBy' : IDL.Text,
});
export const TransportTracker = IDL.Record({
  'id' : IDL.Text,
  'trackingUrl' : IDL.Text,
  'transport' : IDL.Text,
});
export const User = IDL.Record({
  'id' : IDL.Text,
  'username' : IDL.Text,
  'businessIds' : IDL.Vec(IDL.Text),
  'password' : IDL.Text,
  'createdAt' : IDL.Int,
  'role' : Role,
});
export const LoginResult = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBiltyPrefix' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addBusiness' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addDelivery' : IDL.Func([DeliveryEntry], [IDL.Text], []),
  'addGodown' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addInventoryItem' : IDL.Func([InventoryItem], [], []),
  'addQueueEntry' : IDL.Func([QueueEntry], [], []),
  'addSale' : IDL.Func([SaleEntry], [IDL.Text], []),
  'addSubCategory' : IDL.Func([IDL.Text, SubCategory], [], []),
  'addTransitEntry' : IDL.Func([TransitEntry], [], []),
  'addTransportTracker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addTxRecord' : IDL.Func([TxRecord], [], []),
  'addUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'biltyExists' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteBiltyPrefix' : IDL.Func([IDL.Text], [], []),
  'deleteBusiness' : IDL.Func([IDL.Text], [], []),
  'deleteCategory' : IDL.Func([IDL.Text], [], []),
  'deleteGodown' : IDL.Func([IDL.Text], [], []),
  'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
  'deleteInwardSaved' : IDL.Func([IDL.Text], [], []),
  'deleteQueueEntry' : IDL.Func([IDL.Text], [], []),
  'deleteSubCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deleteTransitEntry' : IDL.Func([IDL.Text], [], []),
  'deleteTransportTracker' : IDL.Func([IDL.Text], [], []),
  'deleteTxRecord' : IDL.Func([IDL.Text], [], []),
  'deleteUser' : IDL.Func([IDL.Text], [], []),
  'getBiltyPrefixes' : IDL.Func([], [IDL.Vec(BiltyPrefix)], []),
  'getBusinesses' : IDL.Func([], [IDL.Vec(Business)], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], []),
  'getCurrentUser' : IDL.Func([], [IDL.Text], []),
  'getDeliveries' : IDL.Func([IDL.Text], [IDL.Vec(DeliveryEntry)], []),
  'getGodowns' : IDL.Func([], [IDL.Vec(Godown)], []),
  'getInventory' : IDL.Func([IDL.Text], [IDL.Vec(InventoryItem)], []),
  'getInwardSaved' : IDL.Func([IDL.Text], [IDL.Vec(InwardSavedEntry)], []),
  'getQueueEntries' : IDL.Func([IDL.Text], [IDL.Vec(QueueEntry)], []),
  'getSales' : IDL.Func([IDL.Text], [IDL.Vec(SaleEntry)], []),
  'getTransfers' : IDL.Func([IDL.Text], [IDL.Vec(TransferEntry)], []),
  'getTransitEntries' : IDL.Func([IDL.Text], [IDL.Vec(TransitEntry)], []),
  'getTransportTrackers' : IDL.Func([], [IDL.Vec(TransportTracker)], []),
  'getTxHistory' : IDL.Func([IDL.Text], [IDL.Vec(TxRecord)], []),
  'getUsers' : IDL.Func([], [IDL.Vec(User)], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
  'markQueueDelivered' : IDL.Func([IDL.Text], [], []),
  'postTransfer' : IDL.Func([TransferEntry], [IDL.Text], []),
  'saveInward' : IDL.Func([InwardSavedEntry], [], []),
  'updateBusiness' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateGodown' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateInventoryItem' : IDL.Func([InventoryItem], [], []),
  'updateInwardSaved' : IDL.Func([InwardSavedEntry], [], []),
  'updateQueueEntry' : IDL.Func([QueueEntry], [], []),
  'updateSubCategory' : IDL.Func([IDL.Text, SubCategory], [], []),
  'updateTransitEntry' : IDL.Func([TransitEntry], [], []),
  'updateTransportTracker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DeliveryLineItem = IDL.Record({
    'qty' : IDL.Int,
    'subCategory' : IDL.Text,
    'godownId' : IDL.Text,
    'itemName' : IDL.Text,
    'category' : IDL.Text,
  });
  const DeliveryEntry = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'deliveredBy' : IDL.Text,
    'customerPhone' : IDL.Text,
    'businessId' : IDL.Text,
    'createdAt' : IDL.Int,
    'deliveryType' : IDL.Text,
    'biltyNumber' : IDL.Text,
    'items' : IDL.Vec(DeliveryLineItem),
  });
  const GodownQty = IDL.Record({ 'qty' : IDL.Int, 'godownId' : IDL.Text });
  const InventoryItem = IDL.Record({
    'id' : IDL.Text,
    'subCategory' : IDL.Text,
    'businessId' : IDL.Text,
    'purchaseRate' : IDL.Float64,
    'godownQtys' : IDL.Vec(GodownQty),
    'shopQty' : IDL.Int,
    'itemName' : IDL.Text,
    'category' : IDL.Text,
    'saleRate' : IDL.Float64,
  });
  const QueueBale = IDL.Record({
    'status' : IDL.Text,
    'baleLabel' : IDL.Text,
    'itemName' : IDL.Text,
    'category' : IDL.Text,
  });
  const QueueEntry = IDL.Record({
    'id' : IDL.Text,
    'businessId' : IDL.Text,
    'supplier' : IDL.Text,
    'createdAt' : IDL.Int,
    'transport' : IDL.Text,
    'biltyNumber' : IDL.Text,
    'bales' : IDL.Vec(QueueBale),
    'delivered' : IDL.Bool,
    'enteredBy' : IDL.Text,
  });
  const SaleLineItem = IDL.Record({
    'qty' : IDL.Int,
    'subCategory' : IDL.Text,
    'rate' : IDL.Float64,
    'itemName' : IDL.Text,
    'category' : IDL.Text,
  });
  const SaleEntry = IDL.Record({
    'id' : IDL.Text,
    'businessId' : IDL.Text,
    'createdAt' : IDL.Int,
    'recordedBy' : IDL.Text,
    'items' : IDL.Vec(SaleLineItem),
  });
  const SubCategory = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'fieldType' : IDL.Text,
  });
  const TransitEntry = IDL.Record({
    'id' : IDL.Text,
    'businessId' : IDL.Text,
    'packages' : IDL.Int,
    'supplier' : IDL.Text,
    'createdAt' : IDL.Int,
    'transport' : IDL.Text,
    'biltyNumber' : IDL.Text,
    'itemName' : IDL.Text,
    'category' : IDL.Text,
    'enteredBy' : IDL.Text,
    'biltyDate' : IDL.Text,
  });
  const TxType = IDL.Variant({
    'directStock' : IDL.Null,
    'sale' : IDL.Null,
    'inward' : IDL.Null,
    'delivery' : IDL.Null,
    'transfer' : IDL.Null,
  });
  const TxRecord = IDL.Record({
    'id' : IDL.Text,
    'qty' : IDL.Int,
    'subCategory' : IDL.Text,
    'businessId' : IDL.Text,
    'createdAt' : IDL.Int,
    'rate' : IDL.Float64,
    'transport' : IDL.Text,
    'toLocation' : IDL.Text,
    'fromLocation' : IDL.Text,
    'biltyNumber' : IDL.Text,
    'notes' : IDL.Text,
    'itemName' : IDL.Text,
    'category' : IDL.Text,
    'txType' : TxType,
    'enteredBy' : IDL.Text,
  });
  const Role = IDL.Variant({
    'admin' : IDL.Null,
    'supplier' : IDL.Null,
    'staff' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BiltyPrefix = IDL.Record({ 'id' : IDL.Text, 'prefix' : IDL.Text });
  const Business = IDL.Record({ 'id' : IDL.Text, 'name' : IDL.Text });
  const Category = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'subCategories' : IDL.Vec(SubCategory),
  });
  const Godown = IDL.Record({
    'id' : IDL.Text,
    'businessId' : IDL.Text,
    'name' : IDL.Text,
  });
  const InwardItem = IDL.Record({
    'subCategory' : IDL.Text,
    'purchaseRate' : IDL.Float64,
    'godownQtys' : IDL.Vec(GodownQty),
    'totalQty' : IDL.Int,
    'shopQty' : IDL.Int,
    'itemName' : IDL.Text,
    'category' : IDL.Text,
    'saleRate' : IDL.Float64,
  });
  const InwardSavedEntry = IDL.Record({
    'id' : IDL.Text,
    'businessId' : IDL.Text,
    'supplier' : IDL.Text,
    'transport' : IDL.Text,
    'biltyNumber' : IDL.Text,
    'savedAt' : IDL.Int,
    'savedBy' : IDL.Text,
    'items' : IDL.Vec(InwardItem),
  });
  const TransferEntry = IDL.Record({
    'id' : IDL.Text,
    'qty' : IDL.Int,
    'subCategory' : IDL.Text,
    'businessId' : IDL.Text,
    'createdAt' : IDL.Int,
    'rate' : IDL.Float64,
    'toId' : IDL.Text,
    'toType' : IDL.Text,
    'itemName' : IDL.Text,
    'fromType' : IDL.Text,
    'category' : IDL.Text,
    'fromId' : IDL.Text,
    'transferredBy' : IDL.Text,
  });
  const TransportTracker = IDL.Record({
    'id' : IDL.Text,
    'trackingUrl' : IDL.Text,
    'transport' : IDL.Text,
  });
  const User = IDL.Record({
    'id' : IDL.Text,
    'username' : IDL.Text,
    'businessIds' : IDL.Vec(IDL.Text),
    'password' : IDL.Text,
    'createdAt' : IDL.Int,
    'role' : Role,
  });
  const LoginResult = IDL.Variant({ 'ok' : User, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBiltyPrefix' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addBusiness' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addDelivery' : IDL.Func([DeliveryEntry], [IDL.Text], []),
    'addGodown' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addInventoryItem' : IDL.Func([InventoryItem], [], []),
    'addQueueEntry' : IDL.Func([QueueEntry], [], []),
    'addSale' : IDL.Func([SaleEntry], [IDL.Text], []),
    'addSubCategory' : IDL.Func([IDL.Text, SubCategory], [], []),
    'addTransitEntry' : IDL.Func([TransitEntry], [], []),
    'addTransportTracker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addTxRecord' : IDL.Func([TxRecord], [], []),
    'addUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'biltyExists' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteBiltyPrefix' : IDL.Func([IDL.Text], [], []),
    'deleteBusiness' : IDL.Func([IDL.Text], [], []),
    'deleteCategory' : IDL.Func([IDL.Text], [], []),
    'deleteGodown' : IDL.Func([IDL.Text], [], []),
    'deleteInventoryItem' : IDL.Func([IDL.Text], [], []),
    'deleteInwardSaved' : IDL.Func([IDL.Text], [], []),
    'deleteQueueEntry' : IDL.Func([IDL.Text], [], []),
    'deleteSubCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deleteTransitEntry' : IDL.Func([IDL.Text], [], []),
    'deleteTransportTracker' : IDL.Func([IDL.Text], [], []),
    'deleteTxRecord' : IDL.Func([IDL.Text], [], []),
    'deleteUser' : IDL.Func([IDL.Text], [], []),
    'getBiltyPrefixes' : IDL.Func([], [IDL.Vec(BiltyPrefix)], []),
    'getBusinesses' : IDL.Func([], [IDL.Vec(Business)], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], []),
    'getCurrentUser' : IDL.Func([], [IDL.Text], []),
    'getDeliveries' : IDL.Func([IDL.Text], [IDL.Vec(DeliveryEntry)], []),
    'getGodowns' : IDL.Func([], [IDL.Vec(Godown)], []),
    'getInventory' : IDL.Func([IDL.Text], [IDL.Vec(InventoryItem)], []),
    'getInwardSaved' : IDL.Func([IDL.Text], [IDL.Vec(InwardSavedEntry)], []),
    'getQueueEntries' : IDL.Func([IDL.Text], [IDL.Vec(QueueEntry)], []),
    'getSales' : IDL.Func([IDL.Text], [IDL.Vec(SaleEntry)], []),
    'getTransfers' : IDL.Func([IDL.Text], [IDL.Vec(TransferEntry)], []),
    'getTransitEntries' : IDL.Func([IDL.Text], [IDL.Vec(TransitEntry)], []),
    'getTransportTrackers' : IDL.Func([], [IDL.Vec(TransportTracker)], []),
    'getTxHistory' : IDL.Func([IDL.Text], [IDL.Vec(TxRecord)], []),
    'getUsers' : IDL.Func([], [IDL.Vec(User)], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'login' : IDL.Func([IDL.Text, IDL.Text], [LoginResult], []),
    'markQueueDelivered' : IDL.Func([IDL.Text], [], []),
    'postTransfer' : IDL.Func([TransferEntry], [IDL.Text], []),
    'saveInward' : IDL.Func([InwardSavedEntry], [], []),
    'updateBusiness' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateCategory' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateGodown' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateInventoryItem' : IDL.Func([InventoryItem], [], []),
    'updateInwardSaved' : IDL.Func([InwardSavedEntry], [], []),
    'updateQueueEntry' : IDL.Func([QueueEntry], [], []),
    'updateSubCategory' : IDL.Func([IDL.Text, SubCategory], [], []),
    'updateTransitEntry' : IDL.Func([TransitEntry], [], []),
    'updateTransportTracker' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };