/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BiltyPrefix { 'id' : string, 'prefix' : string }
export interface Business { 'id' : string, 'name' : string }
export interface Category {
  'id' : string,
  'name' : string,
  'subCategories' : Array<SubCategory>,
}
export interface DeliveryEntry {
  'id' : string,
  'customerName' : string,
  'deliveredBy' : string,
  'customerPhone' : string,
  'businessId' : string,
  'createdAt' : bigint,
  'deliveryType' : string,
  'biltyNumber' : string,
  'items' : Array<DeliveryLineItem>,
}
export interface DeliveryLineItem {
  'qty' : bigint,
  'subCategory' : string,
  'godownId' : string,
  'itemName' : string,
  'category' : string,
}
export interface Godown {
  'id' : string,
  'businessId' : string,
  'name' : string,
}
export interface GodownQty { 'qty' : bigint, 'godownId' : string }
export interface InventoryItem {
  'id' : string,
  'subCategory' : string,
  'businessId' : string,
  'purchaseRate' : number,
  'godownQtys' : Array<GodownQty>,
  'shopQty' : bigint,
  'itemName' : string,
  'category' : string,
  'saleRate' : number,
}
export interface InwardItem {
  'subCategory' : string,
  'purchaseRate' : number,
  'godownQtys' : Array<GodownQty>,
  'totalQty' : bigint,
  'shopQty' : bigint,
  'itemName' : string,
  'category' : string,
  'saleRate' : number,
}
export interface InwardSavedEntry {
  'id' : string,
  'businessId' : string,
  'supplier' : string,
  'transport' : string,
  'biltyNumber' : string,
  'savedAt' : bigint,
  'savedBy' : string,
  'items' : Array<InwardItem>,
}
export type LoginResult = { 'ok' : User } |
  { 'err' : string };
export interface QueueBale {
  'status' : string,
  'baleLabel' : string,
  'itemName' : string,
  'category' : string,
}
export interface QueueEntry {
  'id' : string,
  'businessId' : string,
  'supplier' : string,
  'createdAt' : bigint,
  'transport' : string,
  'biltyNumber' : string,
  'bales' : Array<QueueBale>,
  'delivered' : boolean,
  'enteredBy' : string,
}
export type Role = { 'admin' : null } |
  { 'supplier' : null } |
  { 'staff' : null };
export interface SaleEntry {
  'id' : string,
  'businessId' : string,
  'createdAt' : bigint,
  'recordedBy' : string,
  'items' : Array<SaleLineItem>,
}
export interface SaleLineItem {
  'qty' : bigint,
  'subCategory' : string,
  'rate' : number,
  'itemName' : string,
  'category' : string,
}
export interface SubCategory {
  'id' : string,
  'name' : string,
  'options' : Array<string>,
  'fieldType' : string,
}
export interface TransferEntry {
  'id' : string,
  'qty' : bigint,
  'subCategory' : string,
  'businessId' : string,
  'createdAt' : bigint,
  'rate' : number,
  'toId' : string,
  'toType' : string,
  'itemName' : string,
  'fromType' : string,
  'category' : string,
  'fromId' : string,
  'transferredBy' : string,
}
export interface TransitEntry {
  'id' : string,
  'businessId' : string,
  'packages' : bigint,
  'supplier' : string,
  'createdAt' : bigint,
  'transport' : string,
  'biltyNumber' : string,
  'itemName' : string,
  'category' : string,
  'enteredBy' : string,
  'biltyDate' : string,
}
export interface TransportTracker {
  'id' : string,
  'trackingUrl' : string,
  'transport' : string,
}
export interface TxRecord {
  'id' : string,
  'qty' : bigint,
  'subCategory' : string,
  'businessId' : string,
  'createdAt' : bigint,
  'rate' : number,
  'transport' : string,
  'toLocation' : string,
  'fromLocation' : string,
  'biltyNumber' : string,
  'notes' : string,
  'itemName' : string,
  'category' : string,
  'txType' : TxType,
  'enteredBy' : string,
}
export type TxType = { 'directStock' : null } |
  { 'sale' : null } |
  { 'inward' : null } |
  { 'delivery' : null } |
  { 'transfer' : null };
export interface User {
  'id' : string,
  'username' : string,
  'businessIds' : Array<string>,
  'password' : string,
  'createdAt' : bigint,
  'role' : Role,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBiltyPrefix' : ActorMethod<[string, string], undefined>,
  'addBusiness' : ActorMethod<[string, string], undefined>,
  'addCategory' : ActorMethod<[string, string], undefined>,
  'addDelivery' : ActorMethod<[DeliveryEntry], string>,
  'addGodown' : ActorMethod<[string, string, string], undefined>,
  'addInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'addQueueEntry' : ActorMethod<[QueueEntry], undefined>,
  'addSale' : ActorMethod<[SaleEntry], string>,
  'addSubCategory' : ActorMethod<[string, SubCategory], undefined>,
  'addTransitEntry' : ActorMethod<[TransitEntry], undefined>,
  'addTransportTracker' : ActorMethod<[string, string, string], undefined>,
  'addTxRecord' : ActorMethod<[TxRecord], undefined>,
  'addUser' : ActorMethod<
    [string, string, string, Role, Array<string>],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'biltyExists' : ActorMethod<[string], boolean>,
  'deleteBiltyPrefix' : ActorMethod<[string], undefined>,
  'deleteBusiness' : ActorMethod<[string], undefined>,
  'deleteCategory' : ActorMethod<[string], undefined>,
  'deleteGodown' : ActorMethod<[string], undefined>,
  'deleteInventoryItem' : ActorMethod<[string], undefined>,
  'deleteInwardSaved' : ActorMethod<[string], undefined>,
  'deleteQueueEntry' : ActorMethod<[string], undefined>,
  'deleteSubCategory' : ActorMethod<[string, string], undefined>,
  'deleteTransitEntry' : ActorMethod<[string], undefined>,
  'deleteTransportTracker' : ActorMethod<[string], undefined>,
  'deleteTxRecord' : ActorMethod<[string], undefined>,
  'deleteUser' : ActorMethod<[string], undefined>,
  'getBiltyPrefixes' : ActorMethod<[], Array<BiltyPrefix>>,
  'getBusinesses' : ActorMethod<[], Array<Business>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getCurrentUser' : ActorMethod<[], string>,
  'getAppSettings' : ActorMethod<[], string>,
  'saveAppSettings' : ActorMethod<[string], undefined>,
  'getDeliveries' : ActorMethod<[string], Array<DeliveryEntry>>,
  'getGodowns' : ActorMethod<[], Array<Godown>>,
  'getInventory' : ActorMethod<[string], Array<InventoryItem>>,
  'getInwardSaved' : ActorMethod<[string], Array<InwardSavedEntry>>,
  'getQueueEntries' : ActorMethod<[string], Array<QueueEntry>>,
  'getSales' : ActorMethod<[string], Array<SaleEntry>>,
  'getTransfers' : ActorMethod<[string], Array<TransferEntry>>,
  'getTransitEntries' : ActorMethod<[string], Array<TransitEntry>>,
  'getTransportTrackers' : ActorMethod<[], Array<TransportTracker>>,
  'getTxHistory' : ActorMethod<[string], Array<TxRecord>>,
  'getUsers' : ActorMethod<[], Array<User>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'login' : ActorMethod<[string, string], LoginResult>,
  'markQueueDelivered' : ActorMethod<[string], undefined>,
  'postTransfer' : ActorMethod<[TransferEntry], string>,
  'saveInward' : ActorMethod<[InwardSavedEntry], undefined>,
  'updateBusiness' : ActorMethod<[string, string], undefined>,
  'updateCategory' : ActorMethod<[string, string], undefined>,
  'updateGodown' : ActorMethod<[string, string, string], undefined>,
  'updateInventoryItem' : ActorMethod<[InventoryItem], undefined>,
  'updateInwardSaved' : ActorMethod<[InwardSavedEntry], undefined>,
  'updateQueueEntry' : ActorMethod<[QueueEntry], undefined>,
  'updateSubCategory' : ActorMethod<[string, SubCategory], undefined>,
  'updateTransitEntry' : ActorMethod<[TransitEntry], undefined>,
  'updateTransportTracker' : ActorMethod<[string, string, string], undefined>,
  'updateUser' : ActorMethod<
    [string, string, string, Role, Array<string>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];