/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DeliveryEntry {
    id: string;
    customerName: string;
    deliveredBy: string;
    customerPhone: string;
    businessId: string;
    createdAt: bigint;
    deliveryType: string;
    biltyNumber: string;
    items: Array<DeliveryLineItem>;
}
export interface Category {
    id: string;
    name: string;
    subCategories: Array<SubCategory>;
}
export interface BiltyPrefix {
    id: string;
    prefix: string;
}
export interface Business {
    id: string;
    name: string;
}
export interface User {
    id: string;
    username: string;
    businessIds: Array<string>;
    password: string;
    createdAt: bigint;
    role: Role;
}
export interface TransportTracker {
    id: string;
    trackingUrl: string;
    transport: string;
}
export interface QueueBale {
    status: string;
    baleLabel: string;
    itemName: string;
    category: string;
}
export interface SaleLineItem {
    qty: bigint;
    subCategory: string;
    rate: number;
    itemName: string;
    category: string;
}
export interface InwardSavedEntry {
    id: string;
    businessId: string;
    supplier: string;
    transport: string;
    biltyNumber: string;
    savedAt: bigint;
    savedBy: string;
    items: Array<InwardItem>;
}
export interface InventoryItem {
    id: string;
    subCategory: string;
    businessId: string;
    purchaseRate: number;
    godownQtys: Array<GodownQty>;
    shopQty: bigint;
    itemName: string;
    category: string;
    saleRate: number;
}
export interface Godown {
    id: string;
    businessId: string;
    name: string;
}
export interface QueueEntry {
    id: string;
    businessId: string;
    supplier: string;
    createdAt: bigint;
    transport: string;
    biltyNumber: string;
    bales: Array<QueueBale>;
    delivered: boolean;
    enteredBy: string;
}
export interface TransferEntry {
    id: string;
    qty: bigint;
    subCategory: string;
    businessId: string;
    createdAt: bigint;
    rate: number;
    toId: string;
    toType: string;
    itemName: string;
    fromType: string;
    category: string;
    fromId: string;
    transferredBy: string;
}
export interface TxRecord {
    id: string;
    qty: bigint;
    subCategory: string;
    businessId: string;
    createdAt: bigint;
    rate: number;
    transport: string;
    toLocation: string;
    fromLocation: string;
    biltyNumber: string;
    notes: string;
    itemName: string;
    category: string;
    txType: TxType;
    enteredBy: string;
}
export interface TransitEntry {
    id: string;
    businessId: string;
    packages: bigint;
    supplier: string;
    createdAt: bigint;
    transport: string;
    biltyNumber: string;
    itemName: string;
    category: string;
    enteredBy: string;
    biltyDate: string;
}
export type LoginResult = {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
};
export interface SaleEntry {
    id: string;
    businessId: string;
    createdAt: bigint;
    recordedBy: string;
    items: Array<SaleLineItem>;
}
export interface InwardItem {
    subCategory: string;
    purchaseRate: number;
    godownQtys: Array<GodownQty>;
    totalQty: bigint;
    shopQty: bigint;
    itemName: string;
    category: string;
    saleRate: number;
}
export interface GodownQty {
    qty: bigint;
    godownId: string;
}
export interface DeliveryLineItem {
    qty: bigint;
    subCategory: string;
    godownId: string;
    itemName: string;
    category: string;
}
export interface SubCategory {
    id: string;
    name: string;
    options: Array<string>;
    fieldType: string;
}
export enum Role {
    admin = "admin",
    supplier = "supplier",
    staff = "staff"
}
export enum TxType {
    directStock = "directStock",
    sale = "sale",
    inward = "inward",
    delivery = "delivery",
    transfer = "transfer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBiltyPrefix(id: string, prefix: string): Promise<void>;
    addBusiness(id: string, name: string): Promise<void>;
    addCategory(id: string, name: string): Promise<void>;
    addDelivery(entry: DeliveryEntry): Promise<string>;
    addGodown(id: string, name: string, businessId: string): Promise<void>;
    addInventoryItem(item: InventoryItem): Promise<void>;
    addQueueEntry(entry: QueueEntry): Promise<void>;
    addSale(entry: SaleEntry): Promise<string>;
    addSubCategory(categoryId: string, sc: SubCategory): Promise<void>;
    addTransitEntry(entry: TransitEntry): Promise<void>;
    addTransportTracker(id: string, transport: string, trackingUrl: string): Promise<void>;
    addTxRecord(record: TxRecord): Promise<void>;
    addUser(id: string, username: string, password: string, role: Role, businessIds: Array<string>): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    biltyExists(biltyNumber: string): Promise<boolean>;
    deleteBiltyPrefix(id: string): Promise<void>;
    deleteBusiness(id: string): Promise<void>;
    deleteCategory(id: string): Promise<void>;
    deleteGodown(id: string): Promise<void>;
    deleteInventoryItem(id: string): Promise<void>;
    deleteInwardSaved(id: string): Promise<void>;
    deleteQueueEntry(id: string): Promise<void>;
    deleteSubCategory(categoryId: string, subCategoryId: string): Promise<void>;
    deleteTransitEntry(id: string): Promise<void>;
    deleteTransportTracker(id: string): Promise<void>;
    deleteTxRecord(id: string): Promise<void>;
    deleteUser(id: string): Promise<void>;
    getBiltyPrefixes(): Promise<Array<BiltyPrefix>>;
    getBusinesses(): Promise<Array<Business>>;
    getCallerUserRole(): Promise<UserRole>;
    getCategories(): Promise<Array<Category>>;
    getCurrentUser(): Promise<string>;
    getAppSettings(): Promise<string>;
    saveAppSettings(blob: string): Promise<void>;
    getDeliveries(businessId: string): Promise<Array<DeliveryEntry>>;
    getGodowns(): Promise<Array<Godown>>;
    getInventory(businessId: string): Promise<Array<InventoryItem>>;
    getInwardSaved(businessId: string): Promise<Array<InwardSavedEntry>>;
    getQueueEntries(businessId: string): Promise<Array<QueueEntry>>;
    getSales(businessId: string): Promise<Array<SaleEntry>>;
    getTransfers(businessId: string): Promise<Array<TransferEntry>>;
    getTransitEntries(businessId: string): Promise<Array<TransitEntry>>;
    getTransportTrackers(): Promise<Array<TransportTracker>>;
    getTxHistory(businessId: string): Promise<Array<TxRecord>>;
    getUsers(): Promise<Array<User>>;
    isCallerAdmin(): Promise<boolean>;
    login(username: string, password: string): Promise<LoginResult>;
    markQueueDelivered(id: string): Promise<void>;
    postTransfer(entry: TransferEntry): Promise<string>;
    saveInward(entry: InwardSavedEntry): Promise<void>;
    updateBusiness(id: string, name: string): Promise<void>;
    updateCategory(id: string, name: string): Promise<void>;
    updateGodown(id: string, name: string, businessId: string): Promise<void>;
    updateInventoryItem(item: InventoryItem): Promise<void>;
    updateInwardSaved(entry: InwardSavedEntry): Promise<void>;
    updateQueueEntry(entry: QueueEntry): Promise<void>;
    updateSubCategory(categoryId: string, sc: SubCategory): Promise<void>;
    updateTransitEntry(entry: TransitEntry): Promise<void>;
    updateTransportTracker(id: string, transport: string, trackingUrl: string): Promise<void>;
    updateUser(id: string, username: string, password: string, role: Role, businessIds: Array<string>): Promise<void>;
}
import type { LoginResult as _LoginResult, Role as _Role, TxRecord as _TxRecord, TxType as _TxType, User as _User, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBiltyPrefix(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBiltyPrefix(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBiltyPrefix(arg0, arg1);
            return result;
        }
    }
    async addBusiness(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBusiness(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBusiness(arg0, arg1);
            return result;
        }
    }
    async addCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0, arg1);
            return result;
        }
    }
    async addDelivery(arg0: DeliveryEntry): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addDelivery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDelivery(arg0);
            return result;
        }
    }
    async addGodown(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGodown(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGodown(arg0, arg1, arg2);
            return result;
        }
    }
    async addInventoryItem(arg0: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInventoryItem(arg0);
            return result;
        }
    }
    async addQueueEntry(arg0: QueueEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addQueueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addQueueEntry(arg0);
            return result;
        }
    }
    async addSale(arg0: SaleEntry): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addSale(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSale(arg0);
            return result;
        }
    }
    async addSubCategory(arg0: string, arg1: SubCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSubCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSubCategory(arg0, arg1);
            return result;
        }
    }
    async addTransitEntry(arg0: TransitEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransitEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransitEntry(arg0);
            return result;
        }
    }
    async addTransportTracker(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTransportTracker(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTransportTracker(arg0, arg1, arg2);
            return result;
        }
    }
    async addTxRecord(arg0: TxRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTxRecord(to_candid_TxRecord_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTxRecord(to_candid_TxRecord_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addUser(arg0: string, arg1: string, arg2: string, arg3: Role, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addUser(arg0, arg1, arg2, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUser(arg0, arg1, arg2, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async biltyExists(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.biltyExists(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.biltyExists(arg0);
            return result;
        }
    }
    async deleteBiltyPrefix(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBiltyPrefix(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBiltyPrefix(arg0);
            return result;
        }
    }
    async deleteBusiness(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBusiness(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBusiness(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteGodown(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGodown(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGodown(arg0);
            return result;
        }
    }
    async deleteInventoryItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInventoryItem(arg0);
            return result;
        }
    }
    async deleteInwardSaved(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInwardSaved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInwardSaved(arg0);
            return result;
        }
    }
    async deleteQueueEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteQueueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteQueueEntry(arg0);
            return result;
        }
    }
    async deleteSubCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSubCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSubCategory(arg0, arg1);
            return result;
        }
    }
    async deleteTransitEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransitEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransitEntry(arg0);
            return result;
        }
    }
    async deleteTransportTracker(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTransportTracker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTransportTracker(arg0);
            return result;
        }
    }
    async deleteTxRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTxRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTxRecord(arg0);
            return result;
        }
    }
    async deleteUser(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async getBiltyPrefixes(): Promise<Array<BiltyPrefix>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBiltyPrefixes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBiltyPrefixes();
            return result;
        }
    }
    async getBusinesses(): Promise<Array<Business>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBusinesses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBusinesses();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getCurrentUser(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentUser();
            return result;
        }
    }
    async getAppSettings(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getAppSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAppSettings();
            return result;
        }
    }
    async saveAppSettings(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                await this.actor.saveAppSettings(arg0);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            await this.actor.saveAppSettings(arg0);
        }
    }
    async getDeliveries(arg0: string): Promise<Array<DeliveryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeliveries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeliveries(arg0);
            return result;
        }
    }
    async getGodowns(): Promise<Array<Godown>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGodowns();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGodowns();
            return result;
        }
    }
    async getInventory(arg0: string): Promise<Array<InventoryItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInventory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInventory(arg0);
            return result;
        }
    }
    async getInwardSaved(arg0: string): Promise<Array<InwardSavedEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInwardSaved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInwardSaved(arg0);
            return result;
        }
    }
    async getQueueEntries(arg0: string): Promise<Array<QueueEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getQueueEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQueueEntries(arg0);
            return result;
        }
    }
    async getSales(arg0: string): Promise<Array<SaleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSales(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSales(arg0);
            return result;
        }
    }
    async getTransfers(arg0: string): Promise<Array<TransferEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransfers(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransfers(arg0);
            return result;
        }
    }
    async getTransitEntries(arg0: string): Promise<Array<TransitEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransitEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransitEntries(arg0);
            return result;
        }
    }
    async getTransportTrackers(): Promise<Array<TransportTracker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransportTrackers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransportTrackers();
            return result;
        }
    }
    async getTxHistory(arg0: string): Promise<Array<TxRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTxHistory(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTxHistory(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async login(arg0: string, arg1: string): Promise<LoginResult> {
        if (this.processError) {
            try {
                const result = await this.actor.login(arg0, arg1);
                return from_candid_LoginResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.login(arg0, arg1);
            return from_candid_LoginResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async markQueueDelivered(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markQueueDelivered(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markQueueDelivered(arg0);
            return result;
        }
    }
    async postTransfer(arg0: TransferEntry): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.postTransfer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postTransfer(arg0);
            return result;
        }
    }
    async saveInward(arg0: InwardSavedEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveInward(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveInward(arg0);
            return result;
        }
    }
    async updateBusiness(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBusiness(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBusiness(arg0, arg1);
            return result;
        }
    }
    async updateCategory(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1);
            return result;
        }
    }
    async updateGodown(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGodown(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGodown(arg0, arg1, arg2);
            return result;
        }
    }
    async updateInventoryItem(arg0: InventoryItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInventoryItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInventoryItem(arg0);
            return result;
        }
    }
    async updateInwardSaved(arg0: InwardSavedEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInwardSaved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInwardSaved(arg0);
            return result;
        }
    }
    async updateQueueEntry(arg0: QueueEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateQueueEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateQueueEntry(arg0);
            return result;
        }
    }
    async updateSubCategory(arg0: string, arg1: SubCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubCategory(arg0, arg1);
            return result;
        }
    }
    async updateTransitEntry(arg0: TransitEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransitEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransitEntry(arg0);
            return result;
        }
    }
    async updateTransportTracker(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransportTracker(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransportTracker(arg0, arg1, arg2);
            return result;
        }
    }
    async updateUser(arg0: string, arg1: string, arg2: string, arg3: Role, arg4: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_Role_n5(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_LoginResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LoginResult): LoginResult {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_TxRecord_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxRecord): TxRecord {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_TxType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TxType): TxType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_User_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    qty: bigint;
    subCategory: string;
    businessId: string;
    createdAt: bigint;
    rate: number;
    transport: string;
    toLocation: string;
    fromLocation: string;
    biltyNumber: string;
    notes: string;
    itemName: string;
    category: string;
    txType: _TxType;
    enteredBy: string;
}): {
    id: string;
    qty: bigint;
    subCategory: string;
    businessId: string;
    createdAt: bigint;
    rate: number;
    transport: string;
    toLocation: string;
    fromLocation: string;
    biltyNumber: string;
    notes: string;
    itemName: string;
    category: string;
    txType: TxType;
    enteredBy: string;
} {
    return {
        id: value.id,
        qty: value.qty,
        subCategory: value.subCategory,
        businessId: value.businessId,
        createdAt: value.createdAt,
        rate: value.rate,
        transport: value.transport,
        toLocation: value.toLocation,
        fromLocation: value.fromLocation,
        biltyNumber: value.biltyNumber,
        notes: value.notes,
        itemName: value.itemName,
        category: value.category,
        txType: from_candid_TxType_n14(_uploadFile, _downloadFile, value.txType),
        enteredBy: value.enteredBy
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    username: string;
    businessIds: Array<string>;
    password: string;
    createdAt: bigint;
    role: _Role;
}): {
    id: string;
    username: string;
    businessIds: Array<string>;
    password: string;
    createdAt: bigint;
    role: Role;
} {
    return {
        id: value.id,
        username: value.username,
        businessIds: value.businessIds,
        password: value.password,
        createdAt: value.createdAt,
        role: from_candid_Role_n19(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    directStock: null;
} | {
    sale: null;
} | {
    inward: null;
} | {
    delivery: null;
} | {
    transfer: null;
}): TxType {
    return "directStock" in value ? TxType.directStock : "sale" in value ? TxType.sale : "inward" in value ? TxType.inward : "delivery" in value ? TxType.delivery : "transfer" in value ? TxType.transfer : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    supplier: null;
} | {
    staff: null;
}): Role {
    return "admin" in value ? Role.admin : "supplier" in value ? Role.supplier : "staff" in value ? Role.staff : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _User;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: User;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_User_n17(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TxRecord>): Array<TxRecord> {
    return value.map((x)=>from_candid_TxRecord_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n17(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_TxRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxRecord): _TxRecord {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_TxType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): _TxType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    qty: bigint;
    subCategory: string;
    businessId: string;
    createdAt: bigint;
    rate: number;
    transport: string;
    toLocation: string;
    fromLocation: string;
    biltyNumber: string;
    notes: string;
    itemName: string;
    category: string;
    txType: TxType;
    enteredBy: string;
}): {
    id: string;
    qty: bigint;
    subCategory: string;
    businessId: string;
    createdAt: bigint;
    rate: number;
    transport: string;
    toLocation: string;
    fromLocation: string;
    biltyNumber: string;
    notes: string;
    itemName: string;
    category: string;
    txType: _TxType;
    enteredBy: string;
} {
    return {
        id: value.id,
        qty: value.qty,
        subCategory: value.subCategory,
        businessId: value.businessId,
        createdAt: value.createdAt,
        rate: value.rate,
        transport: value.transport,
        toLocation: value.toLocation,
        fromLocation: value.fromLocation,
        biltyNumber: value.biltyNumber,
        notes: value.notes,
        itemName: value.itemName,
        category: value.category,
        txType: to_candid_TxType_n3(_uploadFile, _downloadFile, value.txType),
        enteredBy: value.enteredBy
    };
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TxType): {
    directStock: null;
} | {
    sale: null;
} | {
    inward: null;
} | {
    delivery: null;
} | {
    transfer: null;
} {
    return value == TxType.directStock ? {
        directStock: null
    } : value == TxType.sale ? {
        sale: null
    } : value == TxType.inward ? {
        inward: null
    } : value == TxType.delivery ? {
        delivery: null
    } : value == TxType.transfer ? {
        transfer: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    admin: null;
} | {
    supplier: null;
} | {
    staff: null;
} {
    return value == Role.admin ? {
        admin: null
    } : value == Role.supplier ? {
        supplier: null
    } : value == Role.staff ? {
        staff: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
